# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

xdg-settings set default-web-browser brave-bin.desktop
xdg-settings set default-url-scheme-handler http brave-bin.desktop
xdg-settings set default-url-scheme-handler https brave-bin.desktop

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi
