# /etc/skel/.bash_profile

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

xdg-settings set default-web-browser brave-bin.desktop
xdg-settings set default-url-scheme-handler http brave-bin.desktop
xdg-settings set default-url-scheme-handler https brave-bin.desktop

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi

# This is the list for lf icons:
export LF_ICONS="di=:\
fi=:\
tw=:\
ow=:\
ln=:\
or=❌:\
ex=:\
*.txt=:\
*.png=:\
*.jpg=:\
*.jpeg=:\
*.gif=:\
*.svg=:\
*.xcf=:\
*.html=:\
*.xml=:\
*.h=:\
*.c=:\
*.gch=:\
*.cpp=:\
*.py=:\
*.go=:\
*.java=:\
*.gpg=:\
*.css=:\
*.pdf=:\
*.csv=:\
*.xlsx=:\
*.tex=📜:\
*.md=:\
*.mp3=:\
*.m4a=:\
*.wav=:\
*.mkv=:\
*.mp4=:\
*.webm=:\
*.mpeg=:\
*.avi=:\
*.mov=:\
*.mpg=:\
*.wmv=:\
*.m4b=:\
*.flv=:\
*.zip=:\
*.rar=:\
*.7z=:\
*.tar.gz=:\
*.1=:\
*.nfo=:\
*.info=:\
*.log=:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.jar=♨:\
"

export PATH=$PATH:/etc/gde
